Controllers/ComelecsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Security.Claims;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using VotingSystem.Data;

namespace VotingSystem.Controllers
{
    [Authorize(Roles = "Admin")]
    public class ComelecsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;

        public ComelecsController(ApplicationDbContext context, 
                                UserManager<IdentityUser> userManager,
                                RoleManager<IdentityRole> roleManager)
        {
            _context = context;
            _userManager = userManager;
            _roleManager = roleManager;
        }

        // GET: Comelecs
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Comelecs.Include(c => c.organization);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Comelecs/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var comelecs = await _context.Comelecs
                .Include(c => c.organization)
                .FirstOrDefaultAsync(m => m.id == id);
            if (comelecs == null)
            {
                return NotFound();
            }

            return View(comelecs);
        }

        private async Task AssignRoleToUser(IdentityUser user, string role)
        {
            if (await _roleManager.RoleExistsAsync(role))
            {
                await _userManager.AddToRoleAsync(user, role);
            }
        }
        // GET: Comelecs/Create
        public IActionResult Create()
        {
            ViewData["organizationId"] = new SelectList(_context.Organizations, "id", "name");
            return View();
        }
        public string RandomPassword(int size = 0)
        {
            StringBuilder builder = new StringBuilder();
            builder.Append(RandomString(4, true));
            builder.Append("_");
            builder.Append(RandomNumber(1000, 9999));
            builder.Append(RandomString(2, false));
            return builder.ToString();
        }
        public int RandomNumber(int min, int max)
        {
            Random random = new Random();
            return random.Next(min, max);
        }

        // Generate a random string with a given size and case.
        // If second parameter is true, the return string is lowercase
        public string RandomString(int size, bool lowerCase)
        {
            StringBuilder builder = new StringBuilder();
            Random random = new Random();
            char ch;
            for (int i = 0; i < size; i++)
            {
                ch = Convert.ToChar(Convert.ToInt32(Math.Floor(26 * random.NextDouble() + 65)));
                builder.Append(ch);
            }
            if (lowerCase)
                return builder.ToString().ToLower();
            return builder.ToString();
        }

        // POST: Comelecs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("id,name,user,organizationId, password")] Comelecs comelecs)
        {
            if (ModelState.IsValid)
            {
                string _password = RandomPassword(10);
                var user = new IdentityUser { UserName = comelecs.user, Email = comelecs.user};
                var result = await _userManager.CreateAsync(user, _password);

                Comelecs comelec = new Comelecs();
                comelec.user = comelecs.user;
                comelec.name = comelecs.name;
                comelec.password = _password;
                comelec.organizationId = comelecs.organizationId;

                _context.Add(comelec);
                _context.SaveChanges();

                await AssignRoleToUser(user, "Comelec");
                var claim = new Claim("ComelecsClaim", "True");
                await _userManager.AddClaimAsync(user, new Claim(user.Id, user.Email));
                return RedirectToAction(nameof(Index));
            }
            ViewData["organizationId"] = new SelectList(_context.Organizations, "id", "id", comelecs.organizationId);
            return View(comelecs);
        }

        // GET: Comelecs/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var comelecs = await _context.Comelecs.FindAsync(id);
            if (comelecs == null)
            {
                return NotFound();
            }
            ViewData["organizationId"] = new SelectList(_context.Organizations, "id", "id", comelecs.organizationId);
            return View(comelecs);
        }

        // POST: Comelecs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("id,name,user,organizationId")] Comelecs comelecs)
        {
            if (id != comelecs.id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(comelecs);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ComelecsExists(comelecs.id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["organizationId"] = new SelectList(_context.Organizations, "id", "id", comelecs.organizationId);
            return View(comelecs);
        }

        // GET: Comelecs/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var comelecs = await _context.Comelecs
                .Include(c => c.organization)
                .FirstOrDefaultAsync(m => m.id == id);
            if (comelecs == null)
            {
                return NotFound();
            }

            return View(comelecs);
        }

        // POST: Comelecs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var comelecs = await _context.Comelecs.FindAsync(id);
            _context.Comelecs.Remove(comelecs);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ComelecsExists(int id)
        {
            return _context.Comelecs.Any(e => e.id == id);
        }
    }
}

Controllers/RoleController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel.DataAnnotations;
using System.Threading.Tasks;

namespace Identity.Controllers
{
    [Authorize(Roles = "Admin")]
    public class RoleController : Controller
    {
        private RoleManager<IdentityRole> roleManager;
        public RoleController( RoleManager<IdentityRole> _roleManager)
        {
            roleManager = _roleManager;
        }

        public ViewResult Index() => View(roleManager.Roles);

        private void Errors(IdentityResult result)
        {
            foreach (IdentityError error in result.Errors)
                ModelState.AddModelError("", error.Description);
        }

        public IActionResult Create() => View();

        [HttpPost]
        public async Task<IActionResult> Create([Required] string name)
        {
            if (ModelState.IsValid)
            {
                IdentityResult result = await roleManager.CreateAsync(new IdentityRole(name));
                if (result.Succeeded)
                    return RedirectToAction("Index");
                else
                    Errors(result);
            }
            return View(name);
        }

        //private RoleManager<IdentityRole> roleManager;
        //public RoleController(RoleManager<IdentityRole> roleMgr)
        //{
        //    roleManager = roleMgr;
        //}

        [HttpPost]
        public async Task<IActionResult> Delete(string id)
        {
            IdentityRole role = await roleManager.FindByIdAsync(id);
            if (role != null)
            {
                IdentityResult result = await roleManager.DeleteAsync(role);
                if (result.Succeeded)
                    return RedirectToAction("Index");
                else
                    Errors(result);
            }
            else
                ModelState.AddModelError("", "No role found");
            return View("Index", roleManager.Roles);
        }
    }
}

Controllers/VotersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using VotingSystem.Data;

namespace VotingSystem.Controllers
{
    [Authorize(Roles = "Admin, Comelec")]
    public class VotersController : Controller
    {

        private readonly ApplicationDbContext _context;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;

        public VotersController (ApplicationDbContext context,
                                UserManager<IdentityUser> userManager,
                                RoleManager<IdentityRole> roleManager)
        {
            _context = context;
            _userManager = userManager;
            _roleManager = roleManager;
        }
        private async Task AssignRoleToUser(IdentityUser user, string role)
        {
            if (await _roleManager.RoleExistsAsync(role))
            {
                await _userManager.AddToRoleAsync(user, role);
            }
        }

        // GET: Voters
        public async Task<IActionResult> Index()
        {
            string userName = User.Identity.Name;
            var user = await _userManager.FindByEmailAsync(userName);

            return View(await _context.Voters.ToListAsync());

        }

        // GET: Voters/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var voters = await _context.Voters
                .FirstOrDefaultAsync(m => m.id == id);
            if (voters == null)
            {
                return NotFound();
            }

            return View(voters);
        }

        // GET: Voters/Create
        public string RandomPassword(int size = 0)
        {
            return RandomString(9);
        }

        // Generate a random string of a given size with all upper case characters.
        public string RandomString(int size)
        {
            StringBuilder builder = new StringBuilder();
            Random random = new Random();
            char ch;
            for (int i = 0; i < size; i++)
            {
                ch = Convert.ToChar(Convert.ToInt32(Math.Floor(26 * random.NextDouble() + 65)));
                builder.Append(ch);
            }
            return builder.ToString();
        }

        public IActionResult Create()
        {
            ViewData["organizationId"] = new SelectList(_context.Organizations, "id", "name", "user");
            return View();
        }

    
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("id,name,organizationId, password, user, yearlevel, course, username")] Voters voters)
        {
            if (ModelState.IsValid)
            {

                string _password = RandomPassword(9);
                var user = new IdentityUser { UserName = voters.user, Email = voters.user };
                var result = await _userManager.CreateAsync(user, _password);

                Voters voter = new Voters();
                voter.user = user.Id;   
                voter.name = voters.name;
                voter.password = _password;
                voter.organizationId = voters.organizationId;
                voter.username = user.UserName;
                voter.yearlevel = voters.yearlevel;
                voter.course = voters.course;


                _context.Add(voter);
                _context.SaveChanges();

                await AssignRoleToUser(user, "Voter");
                var claim = new Claim("VotersClaim", "True");
                await _userManager.AddClaimAsync(user, new Claim(user.Id, user.Email));
                return RedirectToAction(nameof(Create));
            }
            ViewData["organizationId"] = new SelectList(_context.Organizations, "id", "name");
            return View(voters);

        }

        // GET: Voters/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var voters = await _context.Voters.FindAsync(id);
            if (voters == null)
            {
                return NotFound();
            }
            return View(voters);
        }

        // POST: Voters/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("id,name,organizationId")] Voters voters)
        {
            if (id != voters.id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(voters);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!VotersExists(voters.id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(voters);
        }

        // GET: Voters/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var voters = await _context.Voters
                .FirstOrDefaultAsync(m => m.id == id);
            if (voters == null)
            {
                return NotFound();
            }

            return View(voters);
        }

        // POST: Voters/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var voters = await _context.Voters.FindAsync(id);
            _context.Voters.Remove(voters);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool VotersExists(int id)
        {
            return _context.Voters.Any(e => e.id == id);
        }
    }
}

Views/Shared/_Layout.cshtml
@inject SignInManager<IdentityUser> SignInManager;
@inject RoleManager<IdentityRole> _roleManager;

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - VotingSystem</title>
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.13.4/css/jquery.dataTables.css" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">VotingSystem</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        @if (SignInManager.IsSignedIn(User))
                        {
                            @if(User.IsInRole("Voter"))
                            {
                                
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Ballots" asp-action="Create">Ballots</a>
                                </li>
                              
                            }
                            @if (User.IsInRole("Admin"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Admins" asp-action="Index">Admin</a>
                                </li>
                              
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Positions" asp-action="Index">Position</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Candidates" asp-action="Index">Candidates</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Voters" asp-action="Index">Voters</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Organizations" asp-action="Index">Organizations</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Role" asp-action="Index">Role</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Comelecs" asp-action="Index">Comelec</a>
                                </li>
                               
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Ballots" asp-action="Index">Ballots</a>
                                </li>
                            }
                            @if (User.IsInRole("Comelec"))
                            {

                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Positions" asp-action="Index">Positions</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Voters" asp-action="Index">Voters</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Candidates" asp-action="Index">Candidates</a>
                                </li>
                            }
                         }
                        
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - VotingSystem - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.datatables.net/1.13.4/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $('#tbllist').DataTable();
        }); 
    </script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>
    